import Link from "next/link";
import classes from "./layout.module.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <div className={classes.violetDiv}>
        <div className={classes.navBar}>
          <Link className={classes.backBtn} href="../">
            Back to editor
          </Link>
          <button className={classes.shareBtn}>Share Link</button>
        </div>
      </div>
      {children}
    </>
  );
}
