import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import classes from "./layout.module.css";

const instrument = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={instrument.className}>
        <main className={classes.loginMain}>
          <div className={classes.loginDiv}>
            <div className={classes.title}>
              <h1 className="headingSmall">devlinks</h1>
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
